flexvolume/smb/deployment/smb-flexvol-installer/smb
Add support for specifying domain in the kubernetes secret.
=> flexvolume/smb: add domain support

flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse
/kind feature
Originally blobfuse is supposed to be under `/usr/bin/blobfuse`, this PR removes the contraints.
Fixes #
```
add blobfuse env support
```
cc @IvanovOleg
=> add blobfuse env support

flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse
/kind feature
Fixes #15
How to test it:
ssh to one node and then run:
```
sudo wget -O /etc/kubernetes/volumeplugins/azure~blobfuse/blobfuse https://raw.githubusercontent.com/andyzhangx/kubernetes-volume-drivers/blobfuse-env/flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse
sudo chmod a+x /etc/kubernetes/volumeplugins/azure~blobfuse/blobfuse 
```
```
add sas token support for blobfuse driver
```
=> add sas token support for blobfuse driver

flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse
/kind feature
Fixes #
```
add driverpath param for blobfuse driver
```
=> add driverpath param for blobfuse driver

.travis.yml, flexvolume/README.md, flexvolume/blobfuse/nginx-flex-blobfuse-pvc.yaml, flexvolume/blobfuse/nginx-flex-blobfuse.yaml, flexvolume/blobfuse/pv-blobfuse-flexvol-gid.yaml, flexvolume/blobfuse/pv-blobfuse-flexvol.yaml, flexvolume/blobfuse/pvc-blobfuse-flexvol.yaml, flexvolume/smb/nginx-flex-smb-pvc.yaml, flexvolume/smb/nginx-flex-smb.yaml, flexvolume/smb/pv-smb-flexvol.yaml, flexvolume/smb/pvc-smb-flexvol.yaml, hack/verify-all.sh, hack/verify-spelling.sh, hack/verify-yamllint.sh
/kind test
test: add some tests
Fixes #
```
none
```
=> test: add some tests

flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.8.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml, flexvolume/smb/deployment/smb-flexvol-installer.yaml, hack/verify-yamllint.sh
chore: fix yaml format
Fixes #
```
```
=> chore: fix yaml format

flexvolume/smb/README.md, flexvolume/smb/deployment/README.md, flexvolume/smb/deployment/smb-flexvol-installer.yaml, flexvolume/smb/deployment/smb-flexvol-installer/install.sh, flexvolume/smb/deployment/smb-flexvol-installer/smb, flexvolume/smb/skaffold.yaml
/kind feature
SMB flexvol 1.0.3: install `jq`, `cifs-utils` by smb-flexvolume image
Fixes #
```
SMB flexvol 1.0.3: install `jq`, `cifs-utils` by smb-flexvolume image
```
=> SMB flexvol 1.0.3

README.md, hack/verify-yamllint.sh, local/README.md, local/deployment.yaml, local/local-pv-provisioner-nvmedisk.yaml, local/local-pv-provisioner-tempdisk.yaml, local/local-pv-storageclass.yaml, local/test.yaml
/kind feature
Fixes #
```
feat: add local pv provisioner
```
=> feat: add local pv provisioner

flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse
/kind bug
fix: mkdir issue on blobfuse 1.2.3
Fixes #58
```
none
```
=> fix: mkdir issue on blobfuse 1.2.3

flexvolume/blobfuse/README.md, flexvolume/blobfuse/deployment/README.md, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.8.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/install.sh
feat: cut blobfuse 1.0.13
Fixes #
```
none
```
=> doc: cut blobfuse 1.0.13

local/local-pv-provisioner-nvmedisk.yaml, local/local-pv-provisioner-tempdisk.yaml
doc: set mcr image for local provisioner
Fixes #62
```
none
```
=> doc: set mcr image for local provisioner

.github/PULL_REQUEST_TEMPLATE.md, hack/verify-yamllint.sh, nfs/README.md, nfs/statefulset-nfs.yaml
doc: add nfs-provisioner docs
Fixes #
```
none
```
=> doc: add nfs-provisioner docs

flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.8.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
During a cluster upgrade we identified blobfuse pods not being scheduled as there is not priority configured. Adding 
priorityClassName: system-node-critical so we can ensure blobfuse will get scheduled as critical pod and not evicted.
 
Fixes #
```
none
```
=> adding priorityClassName

flexvolume/smb/helm/README.md, flexvolume/smb/helm/smb-flexvol/templates/pv-smb-flexvol.yaml
/kind bug
The ability to perform an all-in-one helm installation is a fantastic feature implemented in #49 (shoutout: @snickell!), this PR adds minor fixes.
Tested working on an on-prem MiniKF (Minikube) installation.
=> Fix smb helm chart and instructions

flexvolume/blobfuse/README.md, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.8.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse
/kind feature
fix: blobfuse tmp-path mapping to host & default tmp-path to `/mnt/blobfuse` (which is faster)
Fixes #82
```
fix: blobfuse tmp-path mapping to host
```
=> fix: blobfuse tmp-path mapping to host

flexvolume/blobfuse/README.md, flexvolume/blobfuse/deployment/README.md, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.8.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/install.sh
doc: cut blobfuse 1.0.14
Fixes #
```
doc: cut blobfuse 1.0.14
```
=> doc: cut blobfuse 1.0.14

flexvolume/smb/README.md, flexvolume/smb/deployment/README.md, flexvolume/smb/deployment/smb-flexvol-installer.yaml, flexvolume/smb/deployment/smb-flexvol-installer/install.sh, flexvolume/smb/deployment/smb-flexvol-installer/smb
doc: cut smb 1.0.4
Fixes #
```
doc: cut smb 1.0.4
```
=> doc: cut smb 1.0.4

flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse
/kind bug
fix: pod stuck in terminating issue on 1.18
Fixes #
```
terminating
```
=> fix: pod stuck in terminating issue on 1.18

flexvolume/blobfuse/README.md, flexvolume/blobfuse/deployment/README.md, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.8.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/install.sh, flexvolume/blobfuse/example/deployment.yaml
doc: cut blobfuse 1.0.15
Fixes #
```
doc: cut blobfuse 1.0.15
```
=> doc: cut blobfuse 1.0.15

flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse
/kind bug
fix: use force unmount to fix pod stuck terminating issue
Fixes #
```
fix: use force unmount to fix pod stuck terminating issue
```
=> fix: use force unmount to fix pod stuck terminating issue

flexvolume/blobfuse/README.md, flexvolume/blobfuse/deployment/README.md, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.8.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/install.sh
doc: cut blobfuse 1.0.16
Fixes #
```
doc: cut blobfuse 1.0.16
```
=> doc: cut blobfuse 1.0.16

flexvolume/blobfuse/README.md, flexvolume/blobfuse/deployment/README.md, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.8.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/Dockerfile, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/install.sh
/kind feature
doc: cut blobfuse 1.0.17
Fixes #
```
doc: cut blobfuse 1.0.17
```
=> doc: cut blobfuse 1.0.17

flexvolume/smb/README.md, flexvolume/smb/deployment/README.md, flexvolume/smb/deployment/smb-flexvol-installer.yaml, flexvolume/smb/deployment/smb-flexvol-installer/Dockerfile, flexvolume/smb/deployment/smb-flexvol-installer/install.sh, flexvolume/smb/deployment/smb-flexvol-installer/smb
/kind feature
doc: cut smb 1.0.5
Fixes #
```
doc: cut smb 1.0.5
```
=> doc: cut smb 1.0.5

flexvolume/blobfuse/README.md, flexvolume/blobfuse/deployment/README.md, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.8.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml, flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse
/kind feature
doc: cut blobfuse 1.0.18
Fixes #
```
doc: cut blobfuse 1.0.18
```
=> doc: cut blobfuse 1.0.18

README.md, rook-ceph/README.md, rook-ceph/examples/cluster-on-pvc.yaml, rook-ceph/examples/filesystem.yaml, rook-ceph/examples/nginx.yaml, rook-ceph/examples/operator.yaml
Add instructions and yaml files on how to use Rook Ceph on AKS.
Fixes #
New instructions on how to deploy and use Rook Ceph on Azure Kubernetes Service (AKS).
=> Adding instructions on how to use Rook Ceph on AKS

.github/workflows/static.yaml, local/README.md, local/local-pv-provisioner-nvmedisk.yaml, local/local-pv-provisioner-tempdisk.yaml
/kind bug
fix: add nodeSelector linux and fix doc
Fixes #106
```
fix: add nodeSelector linux and fix doc
```
=> fix: add nodeSelector linux and fix doc

local/local-pv-provisioner-nvmedisk.yaml, local/local-pv-provisioner-tempdisk.yaml
/kind cleanup
chore: set --v=2 for local provisioner
Fixes #
```
none
```
=> chore: set --v=2 for local provisioner

local/README.md, local/deployment.yaml, local/local-pv-provisioner-nvmedisk.yaml, local/local-pv-provisioner-tempdisk.yaml, local/local-pv-storageclass.yaml
doc: refine local volume doc
Fixes #
```
none
```
=> doc: refine local volume doc

local/README.md, local/statefulset.yaml, local/umount-mnt.yaml
add umount-mnt.yaml for local provisioner solution
Fixes #
```
none
```
=> add umount-mnt.yaml for local provisioner solution

README.md, openebs/README.md, openebs/init-openebs-env.yaml
doc: add openebs mayastor doc
Fixes #
```
none
```
=> doc: add openebs mayastor doc

openebs/init-openebs-env.yaml
/kind feature
refine init-openebs-env.yaml with selected labels
Fixes #
```
none
```
=> refine init-openebs-env.yaml with selected labels

hack/verify-all.sh, test/attach_detach_test.sh
>
> /kind bug
> /kind design
> /kind flake
/kind test
test: add a test for attach/detach
Fixes #
```
none
```
=> test: add a test for attach/detach

test/attach_detach_test.sh, test/cyc_attach_detach_test.sh
>
> /kind bug
> /kind design
> /kind flake
/kind design
support loop attach/detach test script in background
Fixes #
```
none
```
=> [test] support loop attach/detach test script in background

test/cyc_attach_detach_test.sh
>
> /kind bug
> /kind design
> /kind flake
/kind design
use curl in cyc_attach_detach_test.sh for attach/detach test
Fixes #
```
none
```
=> [test] use curl in cyc_attach_detach_test.sh for attach/detach test

local/local-pv-provisioner-tempdisk.yaml
/kind bug
fix: use /dev/disk/cloud/azure_resource-part1 for temp disk in local volume discovery
Fixes #
```
fix: use /dev/disk/cloud/azure_resource-part1 for temp disk in local volume discovery
```
=> fix: use /dev/disk/cloud/azure_resource-part1 for temp disk in local volume discovery

test/attach_detach_test.sh, test/attach_detach_test_portworx.sh, test/cyc_attach_detach_test.sh, test/cyc_attach_detach_test_portworx.sh
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
rename attach_detach_test.sh and attach_detach_test_portworx.sh
Fixes #
```
none
```
=> chore: rename attach_detach_test.sh and attach_detach_test_portworx.sh

test/cyc_attach_detach_test.sh
/kind test
test: reduce sleep time
Fixes #
```
none
```
=> test: reduce sleep time

test/README.md, test/pod_failover_test.sh
>
> /kind bug
> /kind design
> /kind flake
/kind desgin
Add pod fail over test script and add README.md file for test guide.
Fixes #
```
none
```
=> Add pod fail over test script and add README.md file for test guide.

test/README.md
>
> /kind bug
> /kind design
> /kind flake
/kind bug
fix: fix README.md file in command
Fixes #
```
none
```
=> fix: fix README.md file

test/attach_detach_test.sh, test/attach_detach_test_portworx.sh
>
> /kind bug
> /kind design
> /kind flake
/kind design
test: add p100 attach/detach test result in attach/detach test script.
clean up detach test code.
fix attach test code since it has one disk mistake.
Fixes #
```
none
```
=> test: add p100 attach/detach test result

test/attach_detach_test.sh, test/attach_detach_test_portworx.sh
>
> /kind bug
> /kind design
> /kind flake
/kind design
test: add sleep 5 min between attach and detach test to avoid detach bug in throttling.
Fixes #
```
none
```
=> test: add sleep 5 min between attach and detach test

local/deployment-ephemeral.yaml, local/local-pv-provisioner-nvmedisk.yaml, local/local-pv-provisioner-tempdisk.yaml
/kind feature
fix: make disk format faster
Original disk format would cost half an hour to format 1TB disk, this PR would use fast format, costing only a few seconds.
This PR also add an deployment example with ephemeral volume mount.
Fixes #
```
fix: make disk format faster
```
=> fix: make disk format faster in local volume example

.github/dependabot.yaml
/kind cleanup
test: add dependabot action
Fixes #
```
none
```
=> test: add dependabot action

local/README.md, local/local-pv-provisioner-nvmedisk.yaml, local/local-pv-provisioner-tempdisk.yaml
/kind feature
chore: upgrade local-volume-provisioner version
Fixes #
```
chore: upgrade local-volume-provisioner version
```
=> chore: upgrade local-volume-provisioner version

test/README.md, test/pod_failover_test_aws.sh, test/pod_failover_test_azure.sh
>
> /kind bug
> /kind design
> /kind flake
/kind test
test: add pod failover test script on aws for comparison test
Fixes #
```
none
```
=> test: add pod failover test script on aws for comparison test
